config/routes.rb
Rails.application.routes.draw do
  resources :day_hours do
    delete 'destroy_all', on: :collection
  end

  root 'application#index'
end

app/models/city.rb
# == Schema Information
#
# Table name: cities
#
#  id         :integer          not null, primary key
#  time_zone  :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class City < ActiveRecord::Base

  has_many :venues

  validates :time_zone, presence: true

end

app/models/day_hour.rb
# == Schema Information
#
# Table name: day_hours
#
#  id           :integer          not null, primary key
#  day          :string
#  opening_time :string
#  closing_time :string
#  venue_id     :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
# Indexes
#
#  index_day_hours_on_venue_id  (venue_id)
#

class DayHour < ActiveRecord::Base

  DAYNAMES = [ 'Default', 'Weekday', 'Weekend' ] + Date::DAYNAMES

  belongs_to :venue

  validates :day, presence: true
  validates :venue, presence: true
  validates :opening_time, presence: true
  validates :closing_time, presence: true

  validate :time_format

  private

    def time_format
      times = [:opening_time, :closing_time]
      times.each do |time|
        parsed_time = Tod::TimeOfDay.try_parse self[time]
        next if parsed_time.present?
        errors.add(time, "needs proper formatting")
      end
    end

end

app/models/venue.rb
# == Schema Information
#
# Table name: venues
#
#  id         :integer          not null, primary key
#  name       :string
#  city_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_venues_on_city_id  (city_id)
#

class Venue < ActiveRecord::Base

  belongs_to :city
  has_many :day_hours

  validates :city, presence: true
  validates :name, presence: true

  def check_availability(datetime)
    datetime = datetime.in_time_zone(city.time_zone)
    desired_time = datetime.strftime("%H:%M:%S")
    opening_times, closing_times = get_hours_for_date datetime
    purge_current_day_hours(opening_times, closing_times)
    return true if is_available? desired_time, opening_times, closing_times

    datetime -= 1.day
    desired_time = datetime.strftime("%H:%M:%S")
    opening_times, closing_times = get_hours_for_date(datetime)
    purge_previous_day_hours(opening_times, closing_times)
    return true if is_available? desired_time, opening_times, closing_times

    return false
  end

  def get_hours_for_date(datetime)
    day_of_week = datetime.strftime("%A").downcase
    is_weekend = datetime.saturday? || datetime.sunday?

    day_descriptions = [
      day_of_week,
      is_weekend ? 'weekend' : 'weekday',
      'default'
    ]
    opening_times = [] ; closing_times = []

    found_appropriate_description = false
    day_descriptions.each do |day_description|
      day_hours.each do |current_hours|
        next unless current_hours.day == day_description
        found_appropriate_description ||= true
        opening_times << current_hours.opening_time
        closing_times << current_hours.closing_time
      end
      break if found_appropriate_description
    end

    return opening_times, closing_times
  end

  private

    def is_available?(desired_time, opening_times, closing_times)
      friendly_time = Tod::TimeOfDay.try_parse(desired_time)
      opening_times.zip(closing_times).each do |opening_time, closing_time|
        next unless friendly_time >= Tod::TimeOfDay.try_parse(opening_time)
        next unless friendly_time <= Tod::TimeOfDay.try_parse(closing_time)
        return true
      end
      return false
    end

    def purge_current_day_hours(opening_times, closing_times)
      number_of_times = closing_times.count
      return if number_of_times.zero?
      (number_of_times-1..0).each do |i|
        friendly_opening_time = Tod::TimeOfDay.try_parse(opening_times[i])
        friendly_closing_time = Tod::TimeOfDay.try_parse(closing_times[i])
        next unless friendly_closing_time <= friendly_opening_time
        closing_times[i] = '23:59:59'
      end
    end

    def purge_previous_day_hours(opening_times, closing_times)
      number_of_times = opening_times.count
      return if number_of_times.zero?
      (number_of_times-1..0).each do |i|
        friendly_opening_time = Tod::TimeOfDay.try_parse(opening_times[i])
        friendly_closing_time = Tod::TimeOfDay.try_parse(closing_times[i])
        if friendly_closing_time <= friendly_opening_time
          opening_times[i] = '00:00:00'
        else
          opening_times.delete_at(i)
          closing_times.delete_at(i)
        end
      end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index
    @days = [*4..6] + [*0..3]
    @times = (0..11).step(1).map{ |i| "#{(11+i)%12+1}am" }
    @times = @times + @times.map{ |t| t.sub('a','p') }
    @venues = Venue.all
  end
end

app/controllers/day_hours_controller.rb
class DayHoursController < ApplicationController
  before_action :set_day_hour, only: [:show, :edit, :update, :destroy]

  # GET /day_hours
  # GET /day_hours.json
  def index
    @day_hours = DayHour.all
  end

  # GET /day_hours/1
  # GET /day_hours/1.json
  def show
  end

  # GET /day_hours/new
  def new
    @day_hour = DayHour.new
  end

  # GET /day_hours/1/edit
  def edit
  end

  # POST /day_hours
  # POST /day_hours.json
  def create
    @day_hour = DayHour.new(day_hour_params)
    respond_to do |format|
      if @day_hour.save
        format.html { redirect_to root_url }
        format.json { render :show, status: :created, location: @day_hour }
      else
        format.html { render :new }
        format.json { render json: @day_hour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /day_hours/1
  # PATCH/PUT /day_hours/1.json
  def update
    respond_to do |format|
      if @day_hour.update(day_hour_params)
        format.html { redirect_to @day_hour, notice: 'Day hour was successfully updated.' }
        format.json { render :show, status: :ok, location: @day_hour }
      else
        format.html { render :edit }
        format.json { render json: @day_hour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /day_hours/1
  # DELETE /day_hours/1.json
  def destroy
    @day_hour.destroy
    respond_to do |format|
      format.html { redirect_to day_hours_url, notice: 'Day hour was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def destroy_all
    Venue.find_by(name: 'New Place').day_hours.all.each do |day_hour|
      day_hour.destroy
    end
    redirect_to root_url, notice: 'New Place successfully restarted'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_day_hour
      @day_hour = DayHour.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def day_hour_params
      day_hour_params = params.require(:day_hour).permit(:venue_id, :opening_time, :closing_time, :day)
      day_hour_params[:opening_time].sub!(/\..*/,'')
      day_hour_params[:closing_time].sub!(/\..*/,'')
      day_hour_params[:day].downcase!
      day_hour_params
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def available?(venue, day, time)
    time_zone = venue.city.time_zone
    datetime = transform_to_datetime(day, time, time_zone)
    venue.check_availability(datetime)
  end

  extend Memoist
  def transform_to_datetime(day, time, time_zone)
    date_and_time  = Date.commercial(
      Date.today.year,
      Date.today.cwday.modulo(4)+Date.today.cweek,
      (day+6)%7+1
    ).to_s
    date_and_time += ' '
    date_and_time += Tod::TimeOfDay.try_parse(time).to_s

    ActiveSupport::TimeZone[time_zone].parse(date_and_time)
  end
  memoize :transform_to_datetime

end

app/helpers/day_hours_helper.rb
module DayHoursHelper
end

app/views/application/_day_hours_table.html.erb
<h2> <%= Date::DAYNAMES[day] %> </h2>

<br>

<table id='dayHours-<%= day %>' class='display'>

  <thead>

    <tr>

      <th class='firstColumn oddHeaderColumn' rowspan='2'>
        Venue
      </th>

      <th class='evenHeaderColumn' colspan='<%= @times.count / 2 %>'>
        <%= Date::DAYNAMES[day] %> Morning
      </th>

      <th class='oddHeaderColumn' colspan='<%= @times.count / 2 %>'>
        <%= Date::DAYNAMES[day] %> Night
      </th>

    </tr>

    <tr>

      <% @times.each_with_index do |time, i| %>
        <% column_class = i < @times.count / 2 ? \
          'evenHeaderColumn' : 'oddHeaderColumn'
        %>
        <th class='<%= column_class %>'>
          <%= time %>
        </th>
      <% end %>

    </tr>

  </thead>

  <tbody>

    <% @venues.each do |venue| %>

      <tr>

        <td class='firstColumn'>
          <% isNewPlace = venue.name == 'New Place' %>
          <% if isNewPlace %> <b> <% end %>
          <%= venue.name %>
          <% if isNewPlace %> </b> <% end %>
        </td>

        <% @times.each do |time| %>

          <td>
            <% if available? venue, day, time %>
              <span class='yes'> &#x2714 </span>
            <% else %>
              <span class='no' > &#x2718 </span>
            <% end %>
          </td>

        <% end %>

      </tr>

    <% end %>

  </tbody>

</table>

app/views/application/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top day-hours-navbar">

  <h1 class='app-name'>
    <%= link_to '#', data: { toggle: "modal", target: "#ajax-modal" } do %>
      Day Hours
    <% end %>
  </h1>

  <h1 class='nav-button'>
    <%= link_to new_day_hour_path, data: { toggle: "modal", target: "#ajax-modal" } do %>
      +
    <% end %>
  </h1>

  <h1 class='nav-button'>
    <%= link_to destroy_all_day_hours_path, :method => :delete do %>
      –
    <% end %>
  </h1>

</nav>

app/views/application/index.html.erb
<%= render partial: 'header' %>

<% @days.each do |day| %>

  <div class="center jumbotron">
    <%= render partial: 'day_hours_table', locals: {day: day} %>
  </div>

  <script>

    var table = $('#dayHours-<%= day %>').DataTable( {
        "scrollY": "300px",
        "scrollX": "100%",
        "scrollCollapse": true,
        "paging": false
    } );
    new $.fn.dataTable.FixedColumns( table );

  </script>

<% end %>

<%= render 'layouts/modal' %>

app/views/day_hours/_form.html.erb
<%= form_for(@day_hour) do |f| %>
  <% if @day_hour.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@day_hour.errors.count, "error") %> prohibited this day_hour from being saved:</h2>

      <ul>
      <% @day_hour.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <% venue = Venue.find_by(name: 'New Place') %>
    <%= f.hidden_field :venue_id, value: venue.id %>
  </div>
  <div class="field">
    <%= f.label :opening_time %><br>
    <%= f.time_field :opening_time, value: Time.parse('10am').strftime('%T.%L') %>
  </div>
  <div class="field">
    <%= f.label :closing_time %><br>
    <%= f.time_field :closing_time, value: Time.parse('10pm').strftime('%T.%L') %>
  </div>
  <div class="field">
    <%= f.label :day %><br>
    <%= f.select :day, DayHour::DAYNAMES %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/day_hours/edit.html.erb
<h1>Editing Day Hour</h1>

<%= render 'form' %>

<%= link_to 'Show', @day_hour %> |
<%= link_to 'Back', day_hours_path %>

app/views/day_hours/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Day Hours</h1>

<table>
  <thead>
    <tr>
      <th>Venue</th>
      <th>Opening time</th>
      <th>Closing time</th>
      <th>Day</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @day_hours.each do |day_hour| %>
      <tr>
        <td><%= day_hour.venue %></td>
        <td><%= day_hour.opening_time %></td>
        <td><%= day_hour.closing_time %></td>
        <td><%= day_hour.day %></td>
        <td><%= link_to 'Show', day_hour %></td>
        <td><%= link_to 'Edit', edit_day_hour_path(day_hour) %></td>
        <td><%= link_to 'Destroy', day_hour, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Day hour', new_day_hour_path %>

app/views/day_hours/new.html.erb
<h1>New Day Hour</h1>

<%= render 'form' %>

app/views/day_hours/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Venue:</strong>
  <%= @day_hour.venue %>
</p>

<p>
  <strong>Opening time:</strong>
  <%= @day_hour.opening_time %>
</p>

<p>
  <strong>Closing time:</strong>
  <%= @day_hour.closing_time %>
</p>

<p>
  <strong>Day:</strong>
  <%= @day_hour.day %>
</p>

<%= link_to 'Edit', edit_day_hour_path(@day_hour) %> |
<%= link_to 'Back', day_hours_path %>

app/views/layouts/_modal.html.erb
<div id="ajax-modal" class="modal" tabindex="-1">

  <div class='modal-header' style='min-height: 50px'>
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3 class="modal-title"></h3>
  </div>

  <div class='modal-body'>
    <img src='http://static1.squarespace.com/static/530153b5e4b098d249d1e931/531793ece4b02cc79a131c6b/531a2076e4b01a2dce5aee01/1394221296348/space-capsule.gif'>
  </div>

  <div class='modal-footer' style='display: none'>
    <button type="button" data-dismiss="modal" class="btn">Close</button>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DayHours</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>